"""probleme competitionsSeasons

Revision ID: 0024d3e9a88c
Revises: 8ef2a8decd5f
Create Date: 2018-07-31 16:20:02.587729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0024d3e9a88c'
down_revision = '8ef2a8decd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions_seasons', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions_seasons', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    # ### end Alembic commands ###
