"""Creation du model Competitions

Revision ID: 0f08bf5590dc
Revises: 1e3824d4afc2
Create Date: 2018-09-07 08:28:22.863140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f08bf5590dc'
down_revision = '1e3824d4afc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitions_names_id', sa.Integer(), nullable=False),
    sa.Column('competitions_categories_id', sa.Integer(), nullable=False),
    sa.Column('competitions_types_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competitions_categories_id'], ['competitions_categories.id'], ),
    sa.ForeignKeyConstraint(['competitions_names_id'], ['competitions_names.id'], ),
    sa.ForeignKeyConstraint(['competitions_types_id'], ['competitions_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tournaments', sa.Column('competitions_id', sa.Integer(), nullable=False))
    op.drop_constraint('tournaments_ibfk_1', 'tournaments', type_='foreignkey')
    op.drop_constraint('tournaments_ibfk_3', 'tournaments', type_='foreignkey')
    op.drop_constraint('tournaments_ibfk_2', 'tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'tournaments', 'competitions', ['competitions_id'], ['id'])
    op.drop_column('tournaments', 'competitions_categories_id')
    op.drop_column('tournaments', 'competitions_types_id')
    op.drop_column('tournaments', 'competitions_names_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('competitions_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('competitions_types_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('competitions_categories_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.create_foreign_key('tournaments_ibfk_2', 'tournaments', 'competitions_names', ['competitions_names_id'], ['id'])
    op.create_foreign_key('tournaments_ibfk_3', 'tournaments', 'competitions_types', ['competitions_types_id'], ['id'])
    op.create_foreign_key('tournaments_ibfk_1', 'tournaments', 'competitions_categories', ['competitions_categories_id'], ['id'])
    op.drop_column('tournaments', 'competitions_id')
    op.drop_table('competitions')
    # ### end Alembic commands ###
