"""liaison geolocalisation et tournaments

Revision ID: 107695db7500
Revises: 98cf493770b5
Create Date: 2018-09-12 07:53:57.310362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '107695db7500'
down_revision = '98cf493770b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('abbreviation', table_name='zones_names')
    # op.drop_index('name', table_name='zones_names')
    # op.drop_table('zones_names')
    # op.drop_table('seasons_names')
    # op.drop_index('abbreviation', table_name='countries_names')
    # op.drop_index('name', table_name='countries_names')
    # op.drop_table('countries_names')
    # op.drop_table('videos_games_names')
    op.add_column('tournaments', sa.Column('geolocalisation_id', sa.Integer(), nullable=False))
    op.drop_constraint('tournaments_ibfk_15', 'tournaments', type_='foreignkey')
    op.drop_constraint('tournaments_ibfk_13', 'tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'tournaments', 'geolocalisation', ['geolocalisation_id'], ['id'])
    op.drop_column('tournaments', 'countries_id')
    op.drop_column('tournaments', 'zones_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('zones_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('countries_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.create_foreign_key('tournaments_ibfk_13', 'tournaments', 'countries', ['countries_id'], ['id'])
    op.create_foreign_key('tournaments_ibfk_15', 'tournaments', 'zones', ['zones_id'], ['id'])
    op.drop_column('tournaments', 'geolocalisation_id')
    op.create_table('videos_games_names',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('countries_names',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('abbreviation', mysql.VARCHAR(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'countries_names', ['name'], unique=True)
    op.create_index('abbreviation', 'countries_names', ['abbreviation'], unique=True)
    op.create_table('seasons_names',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('zones_names',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('abbreviation', mysql.VARCHAR(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'zones_names', ['name'], unique=True)
    op.create_index('abbreviation', 'zones_names', ['abbreviation'], unique=True)
    # ### end Alembic commands ###
