"""reorganisation, class Competitions

Revision ID: 2f3c94e4b39a
Revises: e54ffe4b1c94
Create Date: 2018-08-03 09:37:38.547656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f3c94e4b39a'
down_revision = 'e54ffe4b1c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('competitions_seasons')
    op.drop_constraint('competitions_ibfk_2', 'competitions', type_='foreignkey')
    op.drop_constraint('competitions_ibfk_1', 'competitions', type_='foreignkey')
    op.drop_constraint('competitions_ibfk_5', 'competitions', type_='foreignkey')
    op.drop_constraint('competitions_ibfk_6', 'competitions', type_='foreignkey')
    op.drop_constraint('competitions_ibfk_3', 'competitions', type_='foreignkey')
    op.drop_column('competitions', 'competitions_types_id')
    op.drop_column('competitions', 'zones_id')
    op.drop_column('competitions', 'teams_types_id')
    op.drop_column('competitions', 'competitions_categories_id')
    op.drop_column('competitions', 'countries_id')
    op.drop_constraint('countries_ibfk_1', 'countries', type_='foreignkey')
    op.drop_column('countries', 'zones_id')
    op.drop_constraint('game_teams_ibfk_2', 'game_teams', type_='foreignkey')
    op.drop_constraint('game_teams_ibfk_1', 'game_teams', type_='foreignkey')
    op.drop_constraint('game_teams_ibfk_3', 'game_teams', type_='foreignkey')
    op.drop_column('game_teams', 'zones_id')
    op.drop_column('game_teams', 'countries_id')
    op.drop_column('game_teams', 'teams_types_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_teams', sa.Column('teams_types_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('game_teams', sa.Column('countries_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('game_teams', sa.Column('zones_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('game_teams_ibfk_3', 'game_teams', 'zones', ['zones_id'], ['id'])
    op.create_foreign_key('game_teams_ibfk_1', 'game_teams', 'countries', ['countries_id'], ['id'])
    op.create_foreign_key('game_teams_ibfk_2', 'game_teams', 'teams_types', ['teams_types_id'], ['id'])
    op.add_column('countries', sa.Column('zones_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('countries_ibfk_1', 'countries', 'zones', ['zones_id'], ['id'])
    op.add_column('competitions', sa.Column('countries_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('competitions', sa.Column('competitions_categories_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('competitions', sa.Column('teams_types_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('competitions', sa.Column('zones_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('competitions', sa.Column('competitions_types_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('competitions_ibfk_3', 'competitions', 'countries', ['countries_id'], ['id'])
    op.create_foreign_key('competitions_ibfk_6', 'competitions', 'teams_types', ['teams_types_id'], ['id'])
    op.create_foreign_key('competitions_ibfk_5', 'competitions', 'zones', ['zones_id'], ['id'])
    op.create_foreign_key('competitions_ibfk_1', 'competitions', 'competitions_categories', ['competitions_categories_id'], ['id'])
    op.create_foreign_key('competitions_ibfk_2', 'competitions', 'competitions_types', ['competitions_types_id'], ['id'])
    op.create_table('competitions_seasons',
    sa.Column('seasons_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('competitions_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('teams_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['competitions_id'], ['competitions.id'], name='competitions_seasons_ibfk_1'),
    sa.ForeignKeyConstraint(['seasons_id'], ['seasons.id'], name='competitions_seasons_ibfk_2'),
    sa.ForeignKeyConstraint(['teams_id'], ['game_teams.id'], name='competitions_seasons_ibfk_3'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('games')
    # ### end Alembic commands ###
