"""teams names suppression champs fifa et inversion des autres

Revision ID: 3aaea2f3ec13
Revises: 9ac9bb508095
Create Date: 2018-09-04 16:42:38.736101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3aaea2f3ec13'
down_revision = '9ac9bb508095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams_names', 'fifa_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams_names', sa.Column('fifa_name', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
