"""suppression toutes les primary key sauf id dans competitions

Revision ID: 463ea9f088c2
Revises: 560b1df1f916
Create Date: 2018-08-03 10:21:46.563079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '463ea9f088c2'
down_revision = '560b1df1f916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitions', 'competitions_categories_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competitions', 'competitions_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competitions', 'competitions_types_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competitions', 'countries_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competitions', 'seasons_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competitions', 'teams_levels_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competitions', 'teams_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competitions', 'teams_types_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competitions', 'videos_games_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('competitions', 'zones_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitions', 'zones_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competitions', 'videos_games_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competitions', 'teams_types_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competitions', 'teams_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competitions', 'teams_levels_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competitions', 'seasons_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competitions', 'countries_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competitions', 'competitions_types_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competitions', 'competitions_names_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('competitions', 'competitions_categories_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
