"""empty message

Revision ID: 4d653e60cf77
Revises: 9369beafae1e
Create Date: 2018-06-20 14:42:14.331493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d653e60cf77'
down_revision = '9369beafae1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    op.add_column('roles', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
