"""Renommage Zones, Seasons, VideoGames, Countries

Revision ID: 57a6e9a8fc72
Revises: 6388029d4d3b
Create Date: 2018-09-07 10:06:25.340879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57a6e9a8fc72'
down_revision = '6388029d4d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('abbreviation', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('abbreviation', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tournaments', sa.Column('countries_id', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('videos_games_id', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('zones_id', sa.Integer(), nullable=False))
    op.drop_constraint('tournaments_ibfk_10', 'tournaments', type_='foreignkey')
    op.drop_constraint('tournaments_ibfk_9', 'tournaments', type_='foreignkey')
    op.drop_constraint('tournaments_ibfk_4', 'tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'tournaments', 'countries', ['countries_id'], ['id'])
    op.create_foreign_key(None, 'tournaments', 'videos_games', ['videos_games_id'], ['id'])
    op.create_foreign_key(None, 'tournaments', 'zones', ['zones_id'], ['id'])
    op.drop_column('tournaments', 'zones_names_id')
    op.drop_column('tournaments', 'countries_names_id')
    op.drop_column('tournaments', 'videos_games_names_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('videos_games_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('countries_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('zones_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.create_foreign_key('tournaments_ibfk_4', 'tournaments', 'countries_names', ['countries_names_id'], ['id'])
    op.create_foreign_key('tournaments_ibfk_9', 'tournaments', 'videos_games_names', ['videos_games_names_id'], ['id'])
    op.create_foreign_key('tournaments_ibfk_10', 'tournaments', 'zones_names', ['zones_names_id'], ['id'])
    op.drop_column('tournaments', 'zones_id')
    op.drop_column('tournaments', 'videos_games_id')
    op.drop_column('tournaments', 'countries_id')
    op.create_table('zones_names',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('abbreviation', mysql.VARCHAR(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('seasons_names',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('countries_names',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('abbreviation', mysql.VARCHAR(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('videos_games_names',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('zones')
    op.drop_table('videos_games')
    op.drop_table('seasons')
    op.drop_table('countries')
    # ### end Alembic commands ###
