"""Creation du model Teams

Revision ID: 6388029d4d3b
Revises: 0f08bf5590dc
Create Date: 2018-09-07 08:36:09.156610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6388029d4d3b'
down_revision = '0f08bf5590dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teams_names_id', sa.Integer(), nullable=False),
    sa.Column('teams_types_id', sa.Integer(), nullable=False),
    sa.Column('teams_levels_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teams_levels_id'], ['teams_levels.id'], ),
    sa.ForeignKeyConstraint(['teams_names_id'], ['teams_names.id'], ),
    sa.ForeignKeyConstraint(['teams_types_id'], ['teams_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tournaments', sa.Column('teams_id', sa.Integer(), nullable=False))
    op.drop_constraint('tournaments_ibfk_6', 'tournaments', type_='foreignkey')
    op.drop_constraint('tournaments_ibfk_7', 'tournaments', type_='foreignkey')
    op.drop_constraint('tournaments_ibfk_8', 'tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'tournaments', 'teams', ['teams_id'], ['id'])
    op.drop_column('tournaments', 'teams_types_id')
    op.drop_column('tournaments', 'teams_levels_id')
    op.drop_column('tournaments', 'teams_names_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('teams_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('teams_levels_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('teams_types_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.create_foreign_key('tournaments_ibfk_8', 'tournaments', 'teams_types', ['teams_types_id'], ['id'])
    op.create_foreign_key('tournaments_ibfk_7', 'tournaments', 'teams_names', ['teams_names_id'], ['id'])
    op.create_foreign_key('tournaments_ibfk_6', 'tournaments', 'teams_levels', ['teams_levels_id'], ['id'])
    op.drop_column('tournaments', 'teams_id')
    op.drop_table('teams')
    # ### end Alembic commands ###
