"""ajout relation seasons et competitionseasons

Revision ID: 68d310964a6f
Revises: 2c2bb4292eff
Create Date: 2018-07-30 16:53:25.018952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68d310964a6f'
down_revision = '2c2bb4292eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('competitions_ibfk_4', 'competitions', type_='foreignkey')
    op.create_foreign_key(None, 'competitions', 'teams_types', ['teams_types_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.create_foreign_key('competitions_ibfk_4', 'competitions', 'teams_typeskk', ['teams_types_id'], ['id'])
    # ### end Alembic commands ###
