"""message

Revision ID: 6cb264b0e50d
Revises: 
Create Date: 2018-07-24 16:03:16.749271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb264b0e50d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
