"""empty message

Revision ID: 7615287f956f
Revises: c770629e2926
Create Date: 2018-08-21 18:56:14.261637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7615287f956f'
down_revision = 'c770629e2926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['competitions_competitions_categories_id'], ['competitions.competitions_categories_id'], nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['competitions_competitions_names_id'], ['competitions.competitions_names_id'], nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['competitions_competitions_types_id'], ['competitions.competitions_types_id'], nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('abbreviation', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['competition_countries_names_id'], ['competitions.countries_names_id'], nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('seasons_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['competition_seasons_names_id'], ['competitions.seasons_names_id'], nullable=False),

    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Float(), nullable=True),
     sa.ForeignKeyConstraint(['competitions_teams_levels_id'], ['competitions.teams_levels_id'], nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('teams_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=True),
    sa.Column('fifa_name', sa.String(length=64), nullable=True),
    sa.Column('pes_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['competitions_teams_names_id'], ['competitions.teams_names_id'], nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['competitions_teams_types_id'], ['competitions.teams_types_id'], nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos_games_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['competition_videos_games_names_id'], ['competitions.videos_games_names_id'], nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('abbreviation', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['competition_zones_names_id'], ['competitions.zones_names_id'], nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('videos_games_names_id', sa.Integer(), nullable=True),
    sa.Column('seasons_names_id', sa.Integer(), nullable=True),
    sa.Column('zones_names_id', sa.Integer(), nullable=True),
    sa.Column('countries_names_id', sa.Integer(), nullable=True),
    sa.Column('competitions_types_id', sa.Integer(), nullable=True),
    sa.Column('competitions_categories_id', sa.Integer(), nullable=True),
    sa.Column('competitions_names_id', sa.Integer(), nullable=True),
    sa.Column('teams_names_id', sa.Integer(), nullable=True),
    sa.Column('teams_types_id', sa.Integer(), nullable=True),
    sa.Column('teams_levels_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    pass
