"""modification champs name dans TeamsNames

Revision ID: 8d7e5e56f6b4
Revises: af2355a905b6
Create Date: 2018-08-03 11:10:55.709459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d7e5e56f6b4'
down_revision = 'af2355a905b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams_names', sa.Column('fifa_name', sa.String(length=64), nullable=True))
    op.add_column('teams_names', sa.Column('pes_name', sa.String(length=64), nullable=True))
    op.drop_column('teams_names', 'game_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams_names', sa.Column('game_name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('teams_names', 'pes_name')
    op.drop_column('teams_names', 'fifa_name')
    # ### end Alembic commands ###
