"""Ajout dune table geolocalisation

Revision ID: 98cf493770b5
Revises: 57a6e9a8fc72
Create Date: 2018-09-11 12:07:30.044244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cf493770b5'
down_revision = '57a6e9a8fc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocalisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zones_id', sa.Integer(), nullable=False),
    sa.Column('countries_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['countries_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['zones_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geolocalisation')
    # ### end Alembic commands ###
