"""Competitions devient Tournaments

Revision ID: 9ac9bb508095
Revises: d0aaa377ff27
Create Date: 2018-09-04 09:42:57.438670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ac9bb508095'
down_revision = 'd0aaa377ff27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videos_games_names_id', sa.Integer(), nullable=False),
    sa.Column('seasons_names_id', sa.Integer(), nullable=False),
    sa.Column('zones_names_id', sa.Integer(), nullable=False),
    sa.Column('countries_names_id', sa.Integer(), nullable=False),
    sa.Column('competitions_names_id', sa.Integer(), nullable=False),
    sa.Column('competitions_categories_id', sa.Integer(), nullable=False),
    sa.Column('competitions_types_id', sa.Integer(), nullable=False),
    sa.Column('teams_names_id', sa.Integer(), nullable=False),
    sa.Column('teams_types_id', sa.Integer(), nullable=False),
    sa.Column('teams_levels_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competitions_categories_id'], ['competitions_categories.id'], ),
    sa.ForeignKeyConstraint(['competitions_names_id'], ['competitions_names.id'], ),
    sa.ForeignKeyConstraint(['competitions_types_id'], ['competitions_types.id'], ),
    sa.ForeignKeyConstraint(['countries_names_id'], ['countries_names.id'], ),
    sa.ForeignKeyConstraint(['seasons_names_id'], ['seasons_names.id'], ),
    sa.ForeignKeyConstraint(['teams_levels_id'], ['teams_levels.id'], ),
    sa.ForeignKeyConstraint(['teams_names_id'], ['teams_names.id'], ),
    sa.ForeignKeyConstraint(['teams_types_id'], ['teams_types.id'], ),
    sa.ForeignKeyConstraint(['videos_games_names_id'], ['videos_games_names.id'], ),
    sa.ForeignKeyConstraint(['zones_names_id'], ['zones_names.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('competitions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('videos_games_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('seasons_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('zones_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('countries_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('competitions_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('competitions_categories_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('competitions_types_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('teams_names_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('teams_types_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('teams_levels_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['competitions_categories_id'], ['competitions_categories.id'], name='competitions_ibfk_1'),
    sa.ForeignKeyConstraint(['competitions_names_id'], ['competitions_names.id'], name='competitions_ibfk_2'),
    sa.ForeignKeyConstraint(['competitions_types_id'], ['competitions_types.id'], name='competitions_ibfk_3'),
    sa.ForeignKeyConstraint(['countries_names_id'], ['countries_names.id'], name='competitions_ibfk_4'),
    sa.ForeignKeyConstraint(['seasons_names_id'], ['seasons_names.id'], name='competitions_ibfk_5'),
    sa.ForeignKeyConstraint(['teams_levels_id'], ['teams_levels.id'], name='competitions_ibfk_6'),
    sa.ForeignKeyConstraint(['teams_names_id'], ['teams_names.id'], name='competitions_ibfk_7'),
    sa.ForeignKeyConstraint(['teams_types_id'], ['teams_types.id'], name='competitions_ibfk_8'),
    sa.ForeignKeyConstraint(['videos_games_names_id'], ['videos_games_names.id'], name='competitions_ibfk_9'),
    sa.ForeignKeyConstraint(['zones_names_id'], ['zones_names.id'], name='competitions_ibfk_10'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('tournaments')
    # ### end Alembic commands ###
