"""recréation clés etrangeres

Revision ID: d24d11806715
Revises: 463ea9f088c2
Create Date: 2018-08-03 10:31:49.475958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24d11806715'
down_revision = '463ea9f088c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'competitions', 'competitions_names', ['competitions_names_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'seasons_names', ['seasons_names_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'teams_types', ['teams_types_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'teams_levels', ['teams_levels_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'countries_names', ['countries_names_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'competitions_types', ['competitions_types_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'competitions_categories', ['competitions_categories_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'teams_names', ['teams_names_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'zones_names', ['zones_names_id'], ['id'])
    op.create_foreign_key(None, 'competitions', 'videos_games_names', ['videos_games_names_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    # ### end Alembic commands ###
