"""changement ordre des champs

Revision ID: 0aa735687970
Revises: 409b89487e69
Create Date: 2018-07-27 13:35:09.957039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa735687970'
down_revision = '409b89487e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'game_teams', ['abbreviation'])
    op.create_unique_constraint(None, 'game_teams', ['real_name'])
    op.create_unique_constraint(None, 'game_teams', ['game_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_teams', type_='unique')
    op.drop_constraint(None, 'game_teams', type_='unique')
    op.drop_constraint(None, 'game_teams', type_='unique')
    # ### end Alembic commands ###
