"""renommage champs teams

Revision ID: 135c681c07fe
Revises: 228fc503951b
Create Date: 2018-08-04 19:13:10.604356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '135c681c07fe'
down_revision = '228fc503951b'
branch_labels = None
depends_on = None


def upgrade():pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():pass
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
