"""suppression game_name et real_name pour juste name dans CompetitionsNames

Revision ID: af2355a905b6
Revises: d24d11806715
Create Date: 2018-08-03 10:52:52.592373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af2355a905b6'
down_revision = 'd24d11806715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions_names', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('competitions_names', 'game_name')
    op.drop_column('competitions_names', 'real_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions_names', sa.Column('real_name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('competitions_names', sa.Column('game_name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('competitions_names', 'name')
    # ### end Alembic commands ###
