"""Teams abbreviation pas unique

Revision ID: cc90edbc57c8
Revises: 0aa735687970
Create Date: 2018-07-27 13:41:36.337902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc90edbc57c8'
down_revision = '0aa735687970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('abbreviation', table_name='game_teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('abbreviation', 'game_teams', ['abbreviation'], unique=True)
    # ### end Alembic commands ###
