"""renommage champs, ajout TeamsLevels, VideosGames

Revision ID: ce26d7730734
Revises: 2f3c94e4b39a
Create Date: 2018-08-03 09:45:46.372229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce26d7730734'
down_revision = '2f3c94e4b39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('teams_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=64), nullable=True),
    sa.Column('real_name', sa.String(length=64), nullable=True),
    sa.Column('abbreviation', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_teams')
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('game_teams',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('game_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('real_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('abbreviation', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('videos_games')
    op.drop_table('teams_names')
    op.drop_table('teams_levels')
    # ### end Alembic commands ###
